# Generated by Django 2.2.7 on 2019-12-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20191218_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='comment',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='follow',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='transmit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
