# Generated by Django 2.2.7 on 2019-12-18 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20191218_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='age_60',
            new_name='age_05',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='age_70',
            new_name='age_85',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='age_80',
            new_name='age_95',
        ),
    ]
