# Generated by Django 2.2.7 on 2019-12-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20191218_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='hot',
            field=models.IntegerField(null=True),
        ),
    ]
