# Generated by Django 2.2.7 on 2019-12-22 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_events_hot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['-time'], 'verbose_name': '事件', 'verbose_name_plural': '事件'},
        ),
        migrations.AlterModelOptions(
            name='past_hours_hot',
            options={'verbose_name': '事件热度', 'verbose_name_plural': '事件热度'},
        ),
        migrations.AlterModelOptions(
            name='person_remarks',
            options={'verbose_name': '事件评论', 'verbose_name_plural': '事件评论'},
        ),
        migrations.RemoveField(
            model_name='person_remarks',
            name='person3_reamrk',
        ),
        migrations.RemoveField(
            model_name='person_remarks',
            name='person4_reamrk',
        ),
        migrations.RemoveField(
            model_name='person_remarks',
            name='person5_reamrk',
        ),
        migrations.RemoveField(
            model_name='person_remarks',
            name='person6_reamrk',
        ),
        migrations.AddField(
            model_name='person_remarks',
            name='person3_remark',
            field=models.CharField(default=1, max_length=255, verbose_name='评论3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person_remarks',
            name='person4_remark',
            field=models.CharField(default=1, max_length=255, verbose_name='评论4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person_remarks',
            name='person5_remark',
            field=models.CharField(default=1, max_length=255, verbose_name='评论5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person_remarks',
            name='person6_remark',
            field=models.CharField(default=1, max_length=255, verbose_name='评论6'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='age_00',
            field=models.IntegerField(verbose_name='00后'),
        ),
        migrations.AlterField(
            model_name='events',
            name='age_05',
            field=models.IntegerField(verbose_name='05后'),
        ),
        migrations.AlterField(
            model_name='events',
            name='age_85',
            field=models.IntegerField(verbose_name='85后'),
        ),
        migrations.AlterField(
            model_name='events',
            name='age_90',
            field=models.IntegerField(verbose_name='90后'),
        ),
        migrations.AlterField(
            model_name='events',
            name='age_95',
            field=models.IntegerField(verbose_name='95后'),
        ),
        migrations.AlterField(
            model_name='events',
            name='comment',
            field=models.IntegerField(null=True, verbose_name='评论量'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_description',
            field=models.CharField(max_length=255, verbose_name='事件简介'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_name',
            field=models.CharField(max_length=255, verbose_name='事件名称'),
        ),
        migrations.AlterField(
            model_name='events',
            name='famale',
            field=models.IntegerField(verbose_name='女性'),
        ),
        migrations.AlterField(
            model_name='events',
            name='follow',
            field=models.IntegerField(null=True, verbose_name='点赞量'),
        ),
        migrations.AlterField(
            model_name='events',
            name='hot',
            field=models.CharField(default=1, max_length=255, verbose_name='热度'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='male',
            field=models.IntegerField(verbose_name='男性'),
        ),
        migrations.AlterField(
            model_name='events',
            name='negative_remark',
            field=models.IntegerField(verbose_name='消极评论'),
        ),
        migrations.AlterField(
            model_name='events',
            name='neutral_remark',
            field=models.IntegerField(verbose_name='中性评论'),
        ),
        migrations.AlterField(
            model_name='events',
            name='past_hour_hot',
            field=models.ForeignKey(default=50, on_delete=django.db.models.deletion.CASCADE, to='login.past_hours_hot', verbose_name='过去一小时热度'),
        ),
        migrations.AlterField(
            model_name='events',
            name='positive_remark',
            field=models.IntegerField(verbose_name='积极评论'),
        ),
        migrations.AlterField(
            model_name='events',
            name='relative_person_remark',
            field=models.ForeignKey(default=50, on_delete=django.db.models.deletion.CASCADE, to='login.person_remarks', verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='events',
            name='time',
            field=models.DateField(verbose_name='事件事时间'),
        ),
        migrations.AlterField(
            model_name='events',
            name='transmit',
            field=models.IntegerField(null=True, verbose_name='转发量'),
        ),
        migrations.AlterField(
            model_name='past_hours_hot',
            name='past_fivehour_hot',
            field=models.IntegerField(verbose_name='过去五小时的热度'),
        ),
        migrations.AlterField(
            model_name='past_hours_hot',
            name='past_fourhour_hot',
            field=models.IntegerField(verbose_name='过去四小时的热度'),
        ),
        migrations.AlterField(
            model_name='past_hours_hot',
            name='past_onehour_hot',
            field=models.IntegerField(verbose_name='过去一小时的热度'),
        ),
        migrations.AlterField(
            model_name='past_hours_hot',
            name='past_sixhour_hot',
            field=models.IntegerField(verbose_name='过去六小时的热度'),
        ),
        migrations.AlterField(
            model_name='past_hours_hot',
            name='past_threehour_hot',
            field=models.IntegerField(verbose_name='过去三小时的热度'),
        ),
        migrations.AlterField(
            model_name='past_hours_hot',
            name='past_twohour_hot',
            field=models.IntegerField(verbose_name='过去两小时的热度'),
        ),
        migrations.AlterField(
            model_name='person_remarks',
            name='person1_name',
            field=models.CharField(max_length=255, verbose_name='用户1'),
        ),
        migrations.AlterField(
            model_name='person_remarks',
            name='person1_pic',
            field=models.CharField(max_length=255, verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='person_remarks',
            name='person1_remark',
            field=models.CharField(max_length=255, verbose_name='评论1'),
        ),
        migrations.AlterField(
            model_name='person_remarks',
            name='person2_name',
            field=models.CharField(max_length=255, verbose_name='用户2'),
        ),
        migrations.AlterField(
            model_name='person_remarks',
            name='person2_pic',
            field=models.CharField(max_length=255, verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='person_remarks',
            name='person2_remark',
            field=models.CharField(max_length=255, verbose_name='评论2'),
        ),
        migrations.AlterField(
            model_name='person_remarks',
            name='person3_name',
            field=models.CharField(max_length=255, verbose_name='用户3'),
        ),
        migrations.AlterField(
            model_name='person_remarks',
            name='person3_pic',
            field=models.CharField(max_length=255, verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='person_remarks',
            name='person4_name',
            field=models.CharField(max_length=255, verbose_name='用户4'),
        ),
        migrations.AlterField(
            model_name='person_remarks',
            name='person4_pic',
            field=models.CharField(max_length=255, verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='person_remarks',
            name='person5_name',
            field=models.CharField(max_length=255, verbose_name='用户5'),
        ),
        migrations.AlterField(
            model_name='person_remarks',
            name='person5_pic',
            field=models.CharField(max_length=255, verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='person_remarks',
            name='person6_name',
            field=models.CharField(max_length=255, verbose_name='用户6'),
        ),
        migrations.AlterField(
            model_name='person_remarks',
            name='person6_pic',
            field=models.CharField(max_length=255, verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='电子邮件'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256, verbose_name='用户密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32, verbose_name='用户性别'),
        ),
    ]
