# Generated by Django 2.2.7 on 2019-12-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20191222_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='time',
            field=models.DateTimeField(verbose_name='事件事时间'),
        ),
    ]
