# Generated by Django 2.2.7 on 2019-12-22 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20191222_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='past_hour_hot',
            field=models.ForeignKey(default=50, on_delete=django.db.models.deletion.PROTECT, to='login.past_hours_hot', verbose_name='过去一小时热度'),
        ),
        migrations.AlterField(
            model_name='events',
            name='relative_person_remark',
            field=models.ForeignKey(default=50, on_delete=django.db.models.deletion.PROTECT, to='login.person_remarks', verbose_name='评论数'),
        ),
    ]
