# Generated by Django 2.2.7 on 2019-12-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20191222_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='word_cloud',
            field=models.TextField(null=True),
        ),
    ]
